# Generated by Django 4.1.13 on 2026-06-25 17:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0003_artigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='texto',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterModelTable(
            name='artigo',
            table='artigo',
        ),
    ]
