# Generated by Django 4.1.13 on 2026-06-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0004_alter_artigo_texto_alter_artigo_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='eixotecnologia',
            name='nome',
            field=models.CharField(default='backend', max_length=100),
            preserve_default=False,
        ),
    ]
