# Generated by Django 4.1.13 on 2026-07-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0005_eixotecnologia_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artigo',
            name='titulo',
            field=models.CharField(default='Sem titulo', max_length=200, verbose_name='Título'),
        ),
    ]
