# Generated by Django 4.1.13 on 2026-07-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0006_artigo_foto_artigo_publicada_artigo_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='nivel',
            field=models.CharField(choices=[('B', 'Básico'), ('I', 'Intermediario'), ('A', 'Avançado')], default='B', max_length=1, verbose_name='Nível'),
        ),
    ]
